Mvc.StorageAccount.Demo/Models/EmailMessage.cs
namespace Mvc.StorageAccount.Demo.Models
{
    public class EmailMessage
    {
        public string EmailAddress { get; set; }
        public DateTime TimeStamp { get; set; }
        public string Message { get; set; }
    }
}

Mvc.StorageAccount.Demo/Models/ErrorViewModel.cs
namespace Mvc.StorageAccount.Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc.StorageAccount.Demo/Controllers/AttendeeRegistrationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mvc.StorageAccount.Demo.Data;
using Mvc.StorageAccount.Demo.Models;
using Mvc.StorageAccount.Demo.Services;

namespace Mvc.StorageAccount.Demo.Controllers
{
    public class AttendeeRegistrationController : Controller
    {
        private readonly ITableStorageService _tableStorageService;
        private readonly IBlobStorageService _blobStorageService;
        private readonly IQueueService _queueService;

        public AttendeeRegistrationController(ITableStorageService tableStorageService,
            IBlobStorageService blobStorageService, IQueueService queueService)
        {
            this._tableStorageService = tableStorageService;
            this._blobStorageService = blobStorageService;
            this._queueService = queueService;
        }

        // GET: AttendeeRegistrationController
        public async Task<ActionResult> Index()
        {
            var data = await _tableStorageService.GetAttendees();
            foreach (var item in data)
            {
                item.ImageName = await _blobStorageService.GetBlobUrl(item.ImageName);
            }
            return View(data);
        }

        // GET: AttendeeRegistrationController/Details/5
        public async Task<ActionResult> Details(string id, string industry)
        {
            var data = await _tableStorageService.GetAttendee(industry, id);
            data.ImageName = await _blobStorageService.GetBlobUrl(data.ImageName);
            return View(data);
        }

        // GET: AttendeeRegistrationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AttendeeRegistrationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AttendeeEntity attendeeEntity, 
            IFormFile formFile)
        {
            try
            {
                var id = Guid.NewGuid().ToString();
                attendeeEntity.PartitionKey = attendeeEntity.Industry;
                attendeeEntity.RowKey = id;

                if (formFile?.Length > 0)
                {
                    attendeeEntity.ImageName =
                        await _blobStorageService.UploadBlob(formFile, id);
                }
                else
                {
                    attendeeEntity.ImageName = "default.jpg";
                }

                await _tableStorageService.UpsertAttendee(attendeeEntity);

                var email = new EmailMessage
                {
                    EmailAddress = attendeeEntity.EmailAddress,
                    TimeStamp = DateTime.UtcNow,
                    Message = $"Hello {attendeeEntity.FirstName} {attendeeEntity.LastName}," +
                    $"\n\r Thank you for registering for this event. " +
                    $"\n\r Your record has been saved for future reference. "
                };
                await _queueService.SendMessage(email);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AttendeeRegistrationController/Edit/5
        public async Task<ActionResult> Edit(string id, string industry)
        {
            var data = await _tableStorageService.GetAttendee(industry, id);

            return View(data);
        }

        // POST: AttendeeRegistrationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AttendeeEntity attendeeEntity,
            IFormFile formFile)
        {
            try
            {
                if (formFile?.Length > 0)
                {
                    attendeeEntity.ImageName = await _blobStorageService.UploadBlob(formFile, attendeeEntity.RowKey, attendeeEntity.ImageName);
                }

                attendeeEntity.PartitionKey = attendeeEntity.Industry;
                
                await _tableStorageService.UpsertAttendee(attendeeEntity);

                var email = new EmailMessage
                {
                    EmailAddress = attendeeEntity.EmailAddress,
                    TimeStamp = DateTime.UtcNow,
                    Message = $"Hello {attendeeEntity.FirstName} {attendeeEntity.LastName}," +
                    $"\n\r Your record was modified successfully"
                };
                await _queueService.SendMessage(email);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: AttendeeRegistrationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, string industry)
        {
            try
            {
                var data = await _tableStorageService.GetAttendee(industry, id);
                await _tableStorageService.DeleteAttendee(industry, id);
                await _blobStorageService.RemoveBlob(data.ImageName);

                var email = new EmailMessage
                {
                    EmailAddress = data.EmailAddress,
                    TimeStamp = DateTime.UtcNow,
                    Message = $"Hello {data.FirstName} {data.LastName}," +
                    $"\n\r Your record was removed successfully"
                };
                await _queueService.SendMessage(email);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Mvc.StorageAccount.Demo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.StorageAccount.Demo.Models;
using System.Diagnostics;

namespace Mvc.StorageAccount.Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc.StorageAccount.Demo/Views/AttendeeRegistration/Create.cshtml
@model Mvc.StorageAccount.Demo.Data.AttendeeEntity

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AttendeeEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Upload Avatar</label>
                <input type="file" class="form-control" name="formFile" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Industry" class="control-label"></label>
                <input asp-for="Industry" class="form-control" />
                <span asp-validation-for="Industry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Mvc.StorageAccount.Demo/Views/AttendeeRegistration/DeleteAsync.cshtml
@model Mvc.StorageAccount.Demo.Data.AttendeeEntity

@{
    ViewData["Title"] = "DeleteAsync";
}

<h1>DeleteAsync</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AttendeeEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Industry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Industry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartitionKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartitionKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RowKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RowKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timestamp)
        </dd>
    </dl>
    
    <form asp-action="DeleteAsync">
        <input type="hidden" asp-for="RowKey" name="id" />
        <input type="hidden" asp-for="Industry" name="industry" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Mvc.StorageAccount.Demo/Views/AttendeeRegistration/Details.cshtml
@model Mvc.StorageAccount.Demo.Data.AttendeeEntity

@{
    ViewData["Title"] = "DetailsAsync";
}

<h1>DetailsAsync</h1>

<div>
    <h4>AttendeeEntity</h4>
    <hr />
    <dl class="row">
        
        <dt class="col-sm-2">
            Avatar
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageName" width="150" height="150" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Industry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Industry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartitionKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartitionKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RowKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RowKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timestamp)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Mvc.StorageAccount.Demo/Views/AttendeeRegistration/Edit.cshtml
@model Mvc.StorageAccount.Demo.Data.AttendeeEntity

@{
    ViewData["Title"] = "EditAsync";
}

<h1>EditAsync</h1>

<h4>AttendeeEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RowKey"/>
            <input type="hidden" asp-for="ImageName"/>
            <div class="form-group">
                <label class="control-label">Upload Avatar</label>
                <input type="file" class="form-control" name="formFile" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Industry" class="control-label"></label>
                <input asp-for="Industry" class="form-control" />
                <span asp-validation-for="Industry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Mvc.StorageAccount.Demo/Views/AttendeeRegistration/Index.cshtml
@model IEnumerable<Mvc.StorageAccount.Demo.Data.AttendeeEntity>

@{
    ViewData["Title"] = "IndexAsync";
}

<h1>IndexAsync</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Avatar</th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Industry)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="@item.ImageName" width="50" height="50"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Industry)
            </td>
            <td>
                <form asp-action="Delete">
                    <input type="hidden" value="@item.RowKey" name="id" />
                    <input type="hidden" value="@item.Industry" name="industry" />
                    @Html.ActionLink("Edit", "Edit", new {industry=item.Industry, id=item.RowKey },
                    new{@class="btn btn-warning"})
                    @Html.ActionLink("Details", "Details", new {industry=item.Industry, id=item.RowKey },
                    new{@class="btn btn-primary"})
                    <input type="submit" value="Delete" class="btn btn-danger" /> 
                </form>
                @*@Html.ActionLink("Delete", "Delete", new {industry=item.Industry, id=item.RowKey })*@
            </td>
        </tr>
}
    </tbody>
</table>

Mvc.StorageAccount.Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc.StorageAccount.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc.StorageAccount.Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc.StorageAccount.Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc.StorageAccount.Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AttendeeRegistration" asp-action="Index">Attendee Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mvc.StorageAccount.Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>